### ISSUE TITLE
Usage documentation?

### ISSUE THREAD

**Issue by reggi** [chargebee/chargebee-node#1]
I have a node script that takes in a `CSV` and processes it before we send it off to our fulfillment center.

https://github.com/holstee/node-chargebee-csv

I'd love to hook this up to the api so I don't have to download the `CSV` manually. It can just pull the data and export my own `CSV`.

How can I achieve a pull of all subscriptions in chargebee with this library?

**Comment by reggi** [comment]
I found the [docs here](https://apidocs.chargebee.com/docs/api?lang=node)! It would be nice to add that to the readme!

**Comment by vaibhav1510** [comment]
Hey Thomas. Thank you for notifying it. We have added the ChargeBee API documents link now.
