### ISSUE TITLE
How to enable subscription pause feature for test site

### ISSUE THREAD

**Issue by Zalasanjay** [chargebee/chargebee-node#10]
Hello i'm trying to test subscription pause and resume feature in Node.js for that i execute CURL request to check that how this feature is actually work. CURL request is given bellow
```
curl  https://flow-test.chargebee.com/api/v2/subscriptions/5a5**a92450**00124*cf/pause \
>      -X POST  \
>      -u test_HW**mVhdJd**ucdK0**GC60p4**yi6x2AF:
```
So, i'm getting this error 

> {"message":"Subscription pause feature is currently disabled for you. Contact support@chargebee.com to know more.","type":"invalid_request","api_error_code":"invalid_request","error_code":"pause_feature_not_enabled"}

**Comment by SangeethaBaskaran** [comment]
Hi @Zalasanjay, this API needs the 'Pause subscription' feature to be enabled for your site. Please reach out to [support](support@chargebee.com) to enable this feature from our end.

**Comment by Zalasanjay** [comment]
Thanks i got it...!
