### ISSUE TITLE
**Question** Dynamic API Keys

### ISSUE THREAD

**Issue by tbell511** [chargebee/chargebee-node#11]
Hello!

I am in the process of integrating ChargeBee into a multi-tenant node application.  My clients all have their own ChargeBee accounts.  What is the best way for my app to switch ChargeBee accounts on the fly?
 
Do I just call `chargebee.configure({ site: "clients-site-name", api_key: "clients-api-key"})` before making any call to the chargebee api? 

Thanks!

**Comment by omairvaiyani** [comment]
Hey @formatically, I'm facing the same issue.

For now, upon calling a ```request```, I add the tenant specific config, like so:

```javascript
const tenantConfig = { site: SITE, api_key: tenant.cbApiKey() }
chargebee.subscription.create(options).request(tenantConfig);
```

I believe the ```chargebee.configure``` method is unsafe as it will take effect globally, causing state leak between your clients. 

A better approach would be instantiation, which I don't believe this repository supports at the moment.

Example:

```
const chargebee = require('chargebee');

const getClientForTenant = function (tenantApiKey) {
    // returns an instance which automatically enters the config into requests. 
    return new chargebee.Client({ site: SITE, api_key: tenantApiKey })
}

```

**Comment by abhinav-adtechs** [comment]
Hello! 
I have the same use case, any suggested approach available?

**Comment by cb-tamizhvendansembiyan** [comment]
@abhinav-adtechs You could pass on the site name and the API key at each request level.

A sample code

```js
const newCust = await chargebee.customer.create({
  first_name : "Stuart",
  last_name : "Little"
}).request({
  site: "<YOUR_SITE_NAME>",
  api_key: "<YOUR_SITE_S_API_KEY>",
});
```

Hope it helps and sorry for the delayed response.
