### ISSUE TITLE
Add new endpoints from the May 2019 update

### ISSUE THREAD

**Issue by vthn** [chargebee/chargebee-node#15]
The documentation lists several methods that are not actually available in the current version. e.g. [Get Hierarchy](https://apidocs.chargebee.com/docs/api/customers?lang=node#get_hierarchy) (chargebee.customer.hierarchy) will result in an error.

I'm sure adding these is in the pipeline and I'm submitting this issue more as a reminder for myself, so I can remove my manual:

    [ 
     "hierarchy",
     "GET",
     "/customers",
     "/hierarchy",
     true
    ]

when the update comes out / issue is closed.

That said, I can submit a PR with some of the added endpoints if you'd like.

**Comment by cb-goutham** [comment]
This has been fixed in [v2.5.1](https://github.com/chargebee/chargebee-node/blob/master/CHANGELOG.md#v251-2019-07-08)
