### ISSUE TITLE
Use of deprecated method new Buffer()

### ISSUE THREAD

**Issue by chris-hinds** [chargebee/chargebee-node#28]
https://github.com/chargebee/chargebee-node/blob/f0cf59c4debf350ac8961d3e098b176d1a842a3c/lib/chargebee.js#L222

The above line of code is utilizing `new Buffer()`. new Buffer was deprecated as of NodeJS 8. See [here](https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/) for more info.

This line should simply be able to be replaced with `Buffer.from(string)`.

This issue raises warnings and sometimes errors when running in newer versions of node.

**Comment by cb-goutham** [comment]
This has been addressed in the latest version - [v2.6.6](https://github.com/chargebee/chargebee-node/commit/fae3ee1cab214059799c34e1f7cbefbc72858c09)
