### ISSUE TITLE
Use Promises?

### ISSUE THREAD

**Issue by jzaefferer** [chargebee/chargebee-node#3]
Would it be possible to make this module use promises for all requests? Maybe there's a way to implement that backwards-compatible to the current API?

**Comment by aajitverma001** [comment]
We can understand how cumbersome it is to handle code with callbacks, So we have taken up your request. We will be releasing the module by this week's ends and notify you.

After the change every Resource request function will return a promise for all request.

**Comment by vaibhav1510** [comment]
Added [promise](https://promisesaplus.com/) support in request functions of all resources now in [1.3.2](https://github.com/chargebee/chargebee-node/blob/master/CHANGELOG.md#v132-2016-02-25) version release.

**Comment by Jeger** [comment]
@vaibhav1510 Any chance you could update the documentation with an example of how to use this. I can't seem to get it to work and must be missing something.

**Comment by NickNaso** [comment]
@vaibhav1510 @Jeger  Well documented API is always the best. Thanks for this request so i discoverd that i can use the promise. On the api doc there are only the example on callback. Yes often the method signatures are the same but it could be appreciated a section in docs where this is explicit specified.

**Comment by aajitverma001** [comment]
@Jeger @NickNaso Yes indeed we will update API documentation but in the meantime here are couple of examples which you can refer

```
var chargebee = require("chargebee");
chargebee.configure({
    site: "{site}",
    api_key: "{site_api_key}"
});

chargebee.subscription.create({
    plan_id: "basic",
    customer: {
        email: "john@example.com",
        first_name: "John",
        last_name: "Doe",
        phone: "+1-949-999-9999"
    },
    billing_address: {
        first_name: "John",
        last_name: "Doe",
        line1: "PO Box 9999",
        city: "Walnut",
        state: "California",
        zip: "91789",
        country: "US"
    }
}).request().then(function(result) {
    console.log(result);
    var subscription = result.subscription;
    var customer = result.customer;
    var card = result.card;
    var invoice = result.invoice;
}).catch(function(error) {
    console.log(error);
});

//Promise Chaining
chargebee.subscription.create({
    plan_id: "basic",
    customer: {
        email: "john@example.com",
        first_name: "John",
        last_name: "Doe",
        phone: "+1-949-999-9999"
    }
}).request().then(function(result) {
    var subscription = result.subscription;
    return chargebee.address.update({
        subscription_id: subscription.id,
        label: "shipping_address",
        first_name: "Benjamin",
        last_name: "Ross",
        addr: "PO Box 9999",
        city: "Walnut",
        state: "California",
        zip: "91789",
        country: "United States"
    }).request();
}).then(function(result) {
    console.log(result);
    var address = result.address;
}).catch(function(error) {
    console.log(error);
});
```
Hope this helpful !!

**Comment by NickNaso** [comment]
Great thanks!

**Comment by Jeger** [comment]
@NickNaso Yeah, I was working on wrapping chargebee with promisify when i found this issue :D
It's super awesome that it's supported, and thanks a lot for the fast response with examples @aajitverma001 !

Chargebee is a joy to use atm. :D

**Comment by AlmogCohen** [comment]
I don't think the documentation was updated as I was looking for it and could not find it. If you wish to use `async/await` you can do:

```
try {
  const result = await chargebee.subscription.list({"customer_id[is]": userId}).request();
  console.log('we have the result!')
} catch (error) {
  console.log('we have an error!');
}
```
