### ISSUE TITLE
checkout_onetime methods are missing?

### ISSUE THREAD

**Issue by bneigher** [chargebee/chargebee-node#4]
I'm just noticing that there are two missing methods in this v2 API.

the **hosted_page** endpoints for the following seem to be missing:
- checkout_onetime_addons
- checkout_onetime_charge 

am I missing something?
[https://apidocs.chargebee.com/docs/api/hosted_pages#retrieve_a_hosted_page](https://apidocs.chargebee.com/docs/api/hosted_pages#retrieve_a_hosted_page)

Furthermore will this method be supporting the other Payment Gateways if it will even exist in the v2 API?

**Comment by vaibhav1510** [comment]
Hi Ben,

**checkout_onetime_addons** and **checkout_onetime_charge** APIs were applicable only with 2Checkout gateway. Now, Chargebee does not support these APIs in V2.

If you want to add non-recurring charge or addon, refer the APIs below:

- [Create Invoice For Addon](https://apidocs.chargebee.com/docs/api/invoices#create_invoice_for_addon)

- [Create invoice for charge](https://apidocs.chargebee.com/docs/api/invoices#create_invoice_for_charge)

Contact us at support@chargebee.com if you have any further queries.

**Comment by bneigher** [comment]
thats fine - just update the v2 docs to not have those endpoints :)

**Comment by vaibhav1510** [comment]
Thanks for notifying this Ben. Will update the change logs.
Thanks.
