### ISSUE TITLE
resources/PricingPageSession.d.ts missing

### ISSUE THREAD

**Issue by JanThiel** [chargebee/chargebee-node#44]
### Description of the Bug

2.37.0 introduced "resources/PricingPageSession.d.ts" to the `index.d.ts` yet it did not add the file to the /resources/ folder.

The git commit:

```
64833389 alishsapkota <alish.sapkota@chargebee.com> on 03.07.2024 at 09:01
```

### Steps to reproduce

Compare index.d.ts against the folder content.
Or open the index.d.ts in an IDE (any Jetbrains IDE for example) that checks that kind of stuff. It will highlight the missing file.

### Expected Behavior

File should be there or reference removed

### Operating System

Any

### Language version

Any

### Library version

2.37.0

**Comment by cb-sriramthiagarajan** [comment]
Hi @JanThiel, I'm closing this issue since it's fixed in `v.2.38.0`. Please feel free to reopen this if you're still having this issue. Thanks.

**Comment by JanThiel** [comment]
Thank you 👍
