### ISSUE TITLE
resources/Media.d.ts missing

### ISSUE THREAD

**Issue by JanThiel** [chargebee/chargebee-node#45]
### Description of the Bug

`resources/Media.d.ts` is referenced in `index.d.ts` but does not exist.

### Steps to reproduce

Compare `index.d.ts` against `resource` folder

### Expected Behavior

File exists or reference removed

### Operating System

Any

### Language version

Any

### Library version

2.37.0

**Comment by cb-alish** [comment]
Hi @JanThiel , thanks for reporting this and #44. We'll look into this and get back.

**Comment by cb-alish** [comment]
Hi @JanThiel, this has been fixed in `v2.38.0`. Please give it a try and let us know if it works for you.

**Comment by cb-sriramthiagarajan** [comment]
Hi @JanThiel, I'm closing this issue since it's fixed in `v.2.38.0`. Please feel free to reopen this if you're still having this issue. Thanks.

**Comment by JanThiel** [comment]
Thank you 👍
