### ISSUE TITLE
subscriptions_for_customer method

### ISSUE THREAD

**Issue by NickNaso** [chargebee/chargebee-node#7]
Hi,
I found the method (**subscriptions_for_customer method**) in the code of this module and for me it's ok use it, but i don't know if it's official and if it will be removed in the next releases. So please give me a clarification about that also because there is not any references to it in official documentation.
Thanks in advance.

**Comment by SangeethaBaskaran** [comment]
Hi,

The **subscriptions_for_customer** endpoint  functionality can be achieved through the **list** endpoint with the filter param "customer_id[is]". So,  **subscriptions_for_customer** endpoint has been marked deprecated and hence the reference is missing in the documentation. 

Though it will not be removed any sooner, we prefer you using the latter. Please refer [List subscriptions](https://apidocs.chargebee.com/docs/api/subscriptions#list_subscriptions).

Thanks.
