### ISSUE TITLE
Can't add PayPal as a payment source.

### ISSUE THREAD

**Issue by aigarsdz** [chargebee/chargebee-node#8]
I'm trying to add a new payment source with a type "paypal_express_checkout" to an existing customer, but I get an error saying that the billing agreement id format is incorrect. I've found out that Chargebee is expecting it to start with B, but PayPal billing agreements start with I. 

I'm not sure if this is a problem with this library or Chargebee service itself.

**Comment by SangeethaBaskaran** [comment]
Hi @aigarsdz, We checked at our end and we do not make check if the ID starts with B. However, we check if the BAID number is valid as it syncs with the respective Paypal account. Hence closing the issue. Please report back if you still find this problem.
