### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by alexblack** [chargebee/chargebee-node#9]
Hi, are there typescript typings?

**Comment by SangeethaBaskaran** [comment]
Hi @alexblack, We are working on it but we don't have an ETA on this.

**Comment by tac-aymeric** [comment]
Any news about it ? It'd be so nice !

**Comment by morrislaptop** [comment]
I've started this at https://github.com/morrislaptop/DefinitelyTyped/tree/chargebee/types/chargebee

I will keep going as I go through my project, but it is a lot of work! Help would be appreciated @SangeethaBaskaran @alexblack @tac-aymeric

**Comment by omairvaiyani** [comment]
@morrislaptop hey, are there classes that you'd like us to focus on and submit a PR?

**Comment by remotealex** [comment]
Any updates on this? @SangeethaBaskaran ??

**Comment by jpike88** [comment]
Offical typescript support should be considered essential, please support it.

**Comment by valentinbe** [comment]
+1

**Comment by jpike88** [comment]
@morrislaptop can you publish those types on @types? Doesn't matter if they're incomplete

@SangeethaBaskaran would appreciate an ETA here, and proper attention. Every library I use by 3rd parties has Typescript definitions, it really shouldn't be ok in 2019 to provide something like this to your customers.

**Comment by morrislaptop** [comment]
@jpike88 I'd rather leave it to the owners to decide if they want to use @types or put it in the library. 

You can always pull down my branch and use it locally then contribute back :)

**Comment by jpike88** [comment]
Thanks, I'll get a local copy. Incredibly frustrating though, I feel like I'm using a library from 2010

**Comment by fletling** [comment]
@SangeethaBaskaran or anyone else who's working for chargebee: Your last statement ist from February 2018. Could we get a new official statement about an ETA for typescript types here?

**Comment by jpike88** [comment]
so much for customer support lol

**Comment by remotealex** [comment]
I too would love some proper typings!

**Comment by dreadnautxbuddha** [comment]
Hi @jpike88, how are you using Chargebee in typescript? I'm in development of an Angular app with integrates with Chargebee and I badly need to make requests to the subscriptions API from the client side.

**Comment by jpike88** [comment]
We've decided to use another service.

Feb 2018: "We are working on it but we don't have an ETA on this"

Sep 2019: "..."

I wouldn't use any product like this that didn't have TypeScript as a proper consideration in its SDK. If they're behind the curve in this way then I would assume they are in other ways, and I wouldn't stake something as critical as billing on it.

**Comment by remotealex** [comment]
@dreadnautxbuddha I'm using this for now. Certainly not a final solution but it gets it working: https://gist.github.com/remotealex/6d9753dd6f67912f640c3b68f8e0ef03

**Comment by dreadnautxbuddha** [comment]
> @dreadnautxbuddha I'm using this for now. Certainly not a final solution but it gets it working: https://gist.github.com/remotealex/6d9753dd6f67912f640c3b68f8e0ef03

Wow this is great @remotealex. I'll give it a go some time this week

**Comment by dreadnautxbuddha** [comment]
I feel you @jpike88

**Comment by ConsultDarryl** [comment]
> @dreadnautxbuddha I'm using this for now. Certainly not a final solution but it gets it working: https://gist.github.com/remotealex/6d9753dd6f67912f640c3b68f8e0ef03



> @dreadnautxbuddha I'm using this for now. Certainly not a final solution but it gets it working: https://gist.github.com/remotealex/6d9753dd6f67912f640c3b68f8e0ef03

Feeling the same pain here. Which solution did you switch to?

**Comment by ConsultDarryl** [comment]
> We've decided to use another service.
> 
> Feb 2018: "We are working on it but we don't have an ETA on this"
> 
> Sep 2019: "..."
> 
> I wouldn't use any product like this that didn't have TypeScript as a proper consideration in its SDK. If they're behind the curve in this way then I would assume they are in other ways, and I wouldn't stake something as critical as billing on it.

I feel the same way. Which service did you switch to?

**Comment by Oupsla** [comment]
Hello @cb-gaurav any ETA to deploy official chargebee types ?

Like previously said by other users, it is now critical for a library to provide types in 2020 (especially for a billing library)

**Comment by strothj** [comment]
The documentation is well formatted since it appears to have been generated from tooling on their side. For my client I converted their documentation to HTML AST and ran a transform to TypeScript typings. Unfortunately the code is private but if someone has a day or so of time they should be able to do a conversion.

**Comment by jpike88** [comment]
@strothj is that code available at a price? ;)

**Comment by Oupsla** [comment]
@strothj could you export those types (not the tool) into a gist or a repo ?

**Comment by strothj** [comment]
> @strothj is that code available at a price? ;)

I'll ask the owner next time we have a meeting.

> @strothj could you export those types (not the tool) into a gist or a repo ?

I don't own any of it unfortunately.

**Comment by Oupsla** [comment]
Ok @strothj , could be great in the open source world to publish those types 😄

**Comment by jpike88** [comment]
@ConsultDarryl i know my response is a little late but we’ve stuck to just stripe. It now supports direct debits in Australia which was one of the reasons we looked beyond it, and we also consider a simpler approach to our pricing model which stripes subscriptions can easily support

**Comment by MBrendel** [comment]
@SangeethaBaskaran any news on this topic?
We are just evaluating the usage of Chargebee. Not having Typescript support is a real showstopper!

@strothj could you ask the owner of the code yet? 
Or would it be possible to just share the code you used to generate those types by parsing the HTML AST?

**Comment by mfferreira** [comment]
bump

**Comment by lucbas** [comment]
I actually do not see that big of a benefit in using this library in Typescript when there are no types.
We so far have created interfaces for some objects that we use and iterate over/access, but I think we'll continue in using the url directly.

**Comment by cb-rohitp** [comment]
Hello, everyone!

Official Chargebee update here. We've picked up adding typescript support to our client SDKs. We should have it out in about two weeks!

Will post an update here as soon as it's out.

**Comment by josenriq** [comment]
> Hello, everyone!
> 
> Official Chargebee update here. We've picked up adding typescript support to our client SDKs. We should have it out in about a week!
> 
> Will post an update here as soon as it's out.

Hi. Is this the official package? https://www.npmjs.com/package/chargebee-typescript

**Comment by cb-navaneedhan** [comment]
> > Hello, everyone!
> > Official Chargebee update here. We've picked up adding typescript support to our client SDKs. We should have it out in about a week!
> > Will post an update here as soon as it's out.
> 
> Hi. Is this the official package? https://www.npmjs.com/package/chargebee-typescript

Yes, this is the official package: https://www.npmjs.com/package/chargebee-typescript and please refer to the apidocs: https://apidocs.chargebee.com/docs/api?lang=typescript#versions for downloading, installing and usage.

**Comment by gregoryforel** [comment]
> > @dreadnautxbuddha I'm using this for now. Certainly not a final solution but it gets it working: https://gist.github.com/remotealex/6d9753dd6f67912f640c3b68f8e0ef03
> 
> Wow this is great @remotealex. I'll give it a go some time this week
> 
> **EDIT**
> Hi @remotealex, I tried your typing, and it's working great. However, how did you work around this error?
> 
> > ERROR in ./node_modules/chargebee/lib/chargebee.js
> > Module not found: Error: Can't resolve 'http' in 'node_modules/chargebee/lib'
> > ERROR in ./node_modules/chargebee/lib/chargebee.js
> > Module not found: Error: Can't resolve 'https' in 'node_modules/chargebee/lib'
> > ERROR in ./node_modules/chargebee/lib/chargebee.js
> > Module not found: Error: Can't resolve 'os' in 'node_modules/chargebee/lib'

Hi @dreadnautxbuddha , I know it's been years, but do you have the slightest memory of how you solved the issue? Facing the same error msg. I could get rid of the 'os' one with `yarn add -D os`, but the others are still there. Thanks!

**Comment by strothj** [comment]
@gregoryforel It looks like you're missing the Node typings. Install `@types/node`.

**Comment by gregoryforel** [comment]
For anyone facing the issue, it looks like if you're using `webpack` you need to add this option to your `webpack` config:
```javascript
node: {    
    Buffer: true,
},
```

**Comment by cb-goutham** [comment]
Closing this as Chargebee now supports [typescript SDK](https://github.com/chargebee/chargebee-typescript) officially .
